version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      mysql_server:
        condition: service_started
    entrypoint: ["./wait-for-it.sh", "mysql_server:3306", "--", "gunicorn", "--workers", "3", "--worker-class", "gevent", "--timeout", "300", "-b", "0.0.0.0:3001", "run:app"]
    networks:
      - bridge
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://tml.cs.vt.edu:3001
    networks:
      - bridge
    restart: unless-stopped

  mysql_server:
    build:
      context: ./database
    ports:
      - "3307:3306"
    volumes:
      - ./database/sql_dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bridge
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  bridge:
    driver: bridge